CREATE TABLE IF NOT EXISTS users(
  id TEXT NOT NULL PRIMARY KEY,
  google_id TEXT UNIQUE,
  email TEXT NOT NULL UNIQUE,
  password_hash TEXT,
  created_at INTEGER NOT NULL DEFAULT (unixepoch()),
  CHECK (password_hash IS NOT NULL OR google_id IS NOT NULL)
) STRICT;

CREATE TABLE IF NOT EXISTS todos (
  id INTEGER PRIMARY KEY,
  user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  text TEXT NOT NULL,
  is_done INTEGER NOT NULL DEFAULT 0 CHECK (is_done IN (0, 1)),
  created_at INTEGER NOT NULL DEFAULT (unixepoch())
) STRICT;

CREATE TABLE IF NOT EXISTS sessions (
	id TEXT NOT NULL PRIMARY KEY,
  user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
	secret_hash TEXT NOT NULL, 
	created_at INTEGER NOT NULL
) STRICT;
