CREATE TABLE IF NOT EXISTS todos (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  text TEXT NOT NULL,
  is_done INTEGER NOT NULL DEFAULT 0 CHECK (is_done IN (0, 1)),
  created_at INTEGER NOT NULL DEFAULT (unixepoch())
) STRICT;

CREATE TABLE IF NOT EXISTS session (
	id TEXT NOT NULL PRIMARY KEY,
	secret_hash BLOB NOT NULL, 
	created_at INTEGER NOT NULL DEFAULT (unixepoch())
) STRICT;
